tap "buo/cask-upgrade"
brew "antidote"
brew "fastfetch"
brew "git"
brew "htop"
brew "mas"
brew "pyenv"
brew "pyenv-virtualenv"
brew "rsync"
brew "speedtest-cli"
brew "the_silver_searcher"
brew "tlrc"
brew "tmux"
brew "vim"
brew "zsh"
cask "1password"
cask "1password-cli"
cask "aldente"
cask "alfred"
cask "android-platform-tools"
cask "appcleaner"
cask "baidunetdisk"
cask "balenaetcher"
cask "bartender"
cask "bilibili"
cask "chatgpt"
cask "clash-verge-rev"
cask "daisydisk"
cask "dash@6"
cask "feishu"
cask "fliqlo"
cask "font-jetbrains-mono-nerd-font"
cask "google-chrome"
cask "iina"
cask "iterm2"
cask "itermai"
cask "keka"
cask "monitorcontrol"
cask "moom"
cask "motrix"
cask "neteasemusic"
cask "pdf-expert"
cask "permute"
cask "popclip"
cask "qq"
cask "raycast"
cask "readdle-spark"
cask "squirrel"
cask "steam"
cask "telegram"
cask "the-unarchiver"
cask "visual-studio-code"
cask "wechat"
cask "zotero"
mas "Amphetamine", id: 937984704
mas "Bob", id: 1630034110
mas "Gemini 2", id: 1090488118
mas "Infuse", id: 1136220934
mas "Irvue", id: 1039633667
mas "Keynote", id: 409183694
mas "Maipo", id: 789066512
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Reeder", id: 1529448980
